VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IGDIPlusParam"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'-----------------------------------------------------------------------------------------------------
'
' [Hidennotare] v2.5
'
' Copyright (c) 2019 Yasuhiro Watanabe
' https://github.com/RelaxTools/Hidennotare
' author:relaxtools@opensquare.net
'
' The MIT License (MIT)
'
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
'
' The above copyright notice and this permission notice shall be included in all
' copies or substantial portions of the Software.
'
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
' SOFTWARE.
'
'-----------------------------------------------------------------------------------------------------
'>### IGDIPlusParam インターフェイス
'>
'>**Remarks**
'>
'>IGDIPlusParam のインターフェイス
'>
'>**Definition**
'>
'>```
'>Public Property Let EditType(v As GDIPlusConstants)
'>Public Property Let FileName(v As String)
'>Public Property Let hIcon(v As LongPtr)
'>Public Property Let Width(v As Long)
'>Public Property Let Height(v As Long)
'>Public Property Let color(v As Long)
'>Public Property Set pic(v As IPictureDisp)
'>Public Property Set Shape(v As Object)
'>Public Sub Initialize()
'>Public Sub Run()
'>```
'>
'>**Sample**
'>
'>* None
'>
'-----------------------------------------------------------------------------------------------------
Option Explicit

Public Property Let EditType(v As GDIPlusConstants)

End Property
Public Property Let FileName(v As String)

End Property
Public Property Let hIcon(v As LongPtr)

End Property
Public Property Let Width(v As Long)

End Property
Public Property Let Height(v As Long)

End Property
Public Property Let color(v As Long)

End Property
Public Property Set pic(v As IPictureDisp)

End Property
Public Property Set Shape(v As Object)

End Property
Public Sub Initialize()

End Sub
Public Sub Run()

End Sub

