VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IGDIPlusParam"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Let EditType(v As GDIPlusConstants)

End Property
Public Property Let FileName(v As String)

End Property
Public Property Let hIcon(v As LongPtr)

End Property
Public Property Let Width(v As Long)

End Property
Public Property Let Height(v As Long)

End Property
Public Property Let Color(v As Long)

End Property
Public Property Set Pic(v As IPictureDisp)

End Property
Public Property Set Shape(v As Object)

End Property
Public Sub Initialize()

End Sub
Public Sub Run()

End Sub

