VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ILoggerParam"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let Level(l As LogLevel)

End Property

Public Property Let LogType(l As LogType)

End Property

Public Property Let History(h As Long)

End Property

Public Property Let Folder(f As String)

End Property

Public Property Let Name(n As String)

End Property
Public Sub Init()

End Sub
