VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IMCommand"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Let AliasName(v As String)
End Property
Public Sub Append(m As MTable, Optional ByVal optName As String = "")
End Sub
Public Property Get Table() As MTable
End Property
Public Function ToString()
End Function


